### ISSUE TITLE
Question about swarm & consul integration

### ISSUE THREAD

**Issue by wyhysj** [lowescott/learning-tools#3]
Hi Scott

I have a little question about your blog

http://blog.scottlowe.org/2015/03/06/running-own-docker-swarm-cluster/

I understand the swarm setup, and it's supposed to listen on 2375 port instead of unix socket

But talking about the registrator, I find the --volumn option mapping the unix socket inside container, so when it comes with swarm nodes, how to map the :2375 to /tmp/docker.sock 

Seems not working if you just use --volumn /var/run/docker.sock:/tmp/docker.sock

**Comment by lowescott** [comment]
Hi, thanks for contacting me.

In this setup, the Docker daemon listens to **both** the network socket (TCP port 2375) as well as the local UNIX socket (/var/run/docker.sock). Thus, mapping the Docker UNIX socket into the Registrator container gives that container the ability to listen for Docker events (starting a container, stopping a container, etc.) and use those events to add/remove/update data in the Consul key-value store. Because the Docker daemon is listening to both the network socket and the UNIX socket, we can get by with mapping the UNIX socket into the Registrator container. Does that make sense?

**Comment by wyhysj** [comment]
Hi, Scott, thanks for the reply, I understand now.

**Comment by lowescott** [comment]
Excellent, I'll go ahead and close this issue, then. Thanks!
